"""Tests for the RAG stack: chunker, mock embeddings, retriever, /ask."""
from __future__ import annotations

import math

import pytest
from sqlalchemy import select

from app.models.audit_event import AuditEvent
from app.models.content_item import ContentItem
from app.models.project import Project
from app.services.ai.base import EMBEDDING_DIM
from app.services.ai.mock_provider import MockAIProvider
from app.services.rag.indexer import chunk_markdown, project_document
from app.services.rag.retriever import MockRetriever

BODY = """Intro paragraph before any heading.

## Prerequisites

- A license.

## Steps

1. Do the thing.
2. Check the result.
"""


def test_chunk_markdown_splits_by_heading():
    chunks = chunk_markdown(BODY)
    assert [c.heading for c in chunks] == ["", "Prerequisites", "Steps"]
    assert chunks[0].text.startswith("Intro paragraph")
    assert "Do the thing" in chunks[2].text


def test_chunk_markdown_handles_empty_and_headingless():
    assert chunk_markdown("") == []
    chunks = chunk_markdown("Just one paragraph, no headings.")
    assert len(chunks) == 1
    assert chunks[0].heading == ""


def test_chunk_markdown_splits_oversized_sections():
    body = "## Big\n\n" + "\n\n".join(f"Paragraph {i} " + "x" * 400 for i in range(20))
    chunks = chunk_markdown(body)
    assert len(chunks) > 1
    assert all(c.heading == "Big" for c in chunks)


async def test_mock_embeddings_are_deterministic_and_semantic_ish():
    provider = MockAIProvider()
    [a1] = await provider.embed(["analyze the budget variance report in excel"])
    [a2] = await provider.embed(["analyze the budget variance report in excel"])
    [b] = await provider.embed(["budget variance analysis for excel tables"])
    [c] = await provider.embed(["quantum entanglement pizza recipes"])

    assert len(a1) == EMBEDDING_DIM
    assert a1 == a2  # deterministic

    def cosine(u, v):
        return sum(x * y for x, y in zip(u, v, strict=True))

    assert math.isclose(cosine(a1, a1), 1.0, rel_tol=1e-9)
    # Overlapping vocabulary must beat unrelated text by a wide margin.
    assert cosine(a1, b) > 0.3
    assert cosine(a1, c) < 0.05


def test_project_document_includes_key_fields():
    row = Project(
        id=7,
        name="Invoice triage copilot",
        status="pilot",
        department="Finance",
        summary="Routes invoices automatically.",
        tools_used=["Power Automate"],
    )
    doc = project_document(row)
    assert "Invoice triage copilot" in doc
    assert "status: pilot" in doc
    assert "Power Automate" in doc


@pytest.fixture
def rag_data(db_session):
    rows = [
        ContentItem(
            slug="copilot-excel-budget-variance",
            kind="playbook",
            title="Analyze a budget variance report with Copilot in Excel",
            summary="Summarize month-over-month variances in a budget report.",
            body_md="## Steps\nAsk Copilot to add a variance column to the table.",
            tags=["budget"],
            attributes={},
            related_slugs=[],
        ),
        ContentItem(
            slug="unpublished",
            kind="playbook",
            title="Secret budget draft",
            summary="budget budget budget",
            body_md="budget",
            tags=[],
            attributes={},
            related_slugs=[],
            published=False,
        ),
        Project(
            name="Invoice OCR pilot",
            status="pilot",
            department="Finance",
            summary="Extract invoice fields with OCR.",
            tools_used=[],
            related_slugs=[],
        ),
    ]
    db_session.add_all(rows)
    db_session.commit()
    yield rows
    for row in rows:
        db_session.delete(row)
    db_session.query(AuditEvent).delete()
    db_session.commit()


async def test_mock_retriever_ranks_and_excludes_unpublished(db_session, rag_data):
    results = await MockRetriever().search(db_session, "budget variance excel", k=5)
    assert results
    assert results[0].ref == "copilot-excel-budget-variance"
    assert all(r.ref != "unpublished" for r in results)


async def test_mock_retriever_finds_projects(db_session, rag_data):
    results = await MockRetriever().search(db_session, "invoice ocr", k=5)
    assert any(r.source_type == "project" for r in results)


def test_ask_returns_grounded_answer_with_citations(client, db_session, rag_data):
    resp = client.post(
        "/api/v1/ask", json={"question": "How do I analyze a budget variance in Excel?"}
    )
    assert resp.status_code == 200
    body = resp.json()
    assert body["grounded"] is True
    assert "[mock]" in body["answer"]  # generated by the mock chat provider
    refs = [c["sourceKey"] for c in body["citations"]]
    assert "copilot-excel-budget-variance" in refs
    assert "unpublished" not in refs

    events = db_session.execute(
        select(AuditEvent).where(AuditEvent.action == "ask.completed")
    ).scalars().all()
    assert len(events) == 1


def test_ask_falls_back_without_llm_call_when_nothing_matches(client, rag_data):
    resp = client.post("/api/v1/ask", json={"question": "zzzqqq xyzzy frobnicate"})
    assert resp.status_code == 200
    body = resp.json()
    assert body["grounded"] is False
    assert body["citations"] == []
    assert "[mock]" not in body["answer"]  # the LLM was never called


def test_ask_validates_question_length(client):
    assert client.post("/api/v1/ask", json={"question": "hi"}).status_code == 422
