"""/api/v1/ask — grounded Q&A over guides, prompts, and the project inventory.

Retrieval-augmented: top-k chunks come from the pgvector index (or the keyword
fallback outside Postgres), the answer is generated by the configured
AIProvider constrained to that context, and every response carries citations.
"""
from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session

from app.core.config import Settings, get_settings
from app.db.session import get_db
from app.schemas.ask import AskRequest, AskResponse, Citation
from app.schemas.common import ErrorResponse
from app.services.ai.base import AIProvider, ChatMessage
from app.services.ai.factory import get_ai_provider
from app.services.audit import record_event
from app.services.identity.current_user import CurrentUser
from app.services.rag.retriever import RetrievedSource, Retriever, get_retriever

router = APIRouter(tags=["ask"])

ASK_ERROR_RESPONSES = {
    401: {"model": ErrorResponse, "description": "Missing or invalid bearer token."},
    422: {"model": ErrorResponse, "description": "Request validation failed."},
    500: {"model": ErrorResponse, "description": "Unexpected server error."},
    502: {"model": ErrorResponse, "description": "Upstream AI provider failure."},
}

SYSTEM_PROMPT = (
    "You are the assistant for Nimbus, the internal AI enablement hub for Finance & "
    "Operations staff. Answer the user's question using ONLY the numbered context "
    "sources below. Cite sources inline as [1], [2], ... after the statements they "
    "support. If the context does not cover the question, say so plainly and point "
    "the user to the closest relevant source instead of guessing. Be concise and "
    "practical."
)

FALLBACK_ANSWER = (
    "I couldn't find anything in Nimbus that covers that. Try browsing the guides, "
    "the prompt library, or the project inventory — or rephrase your question with "
    "the tool or task you have in mind."
)

_MAX_CONTEXT_CHARS_PER_SOURCE = 2400


def ai_provider(settings: Annotated[Settings, Depends(get_settings)]) -> AIProvider:
    return get_ai_provider(settings)


def retriever(
    db: Annotated[Session, Depends(get_db)],
    provider: Annotated[AIProvider, Depends(ai_provider)],
) -> Retriever:
    return get_retriever(db, provider)


def _source_label(source: RetrievedSource) -> str:
    label = f"{source.title} ({source.kind})"
    if source.heading:
        label += f" — {source.heading}"
    return label


def build_grounded_prompt(question: str, sources: list[RetrievedSource]) -> str:
    blocks = [
        f"[{i}] {_source_label(s)}\n{s.text[:_MAX_CONTEXT_CHARS_PER_SOURCE]}"
        for i, s in enumerate(sources, start=1)
    ]
    context = "\n\n---\n\n".join(blocks)
    return f"Context sources:\n\n{context}\n\n---\n\nQuestion: {question}"


def _citations(sources: list[RetrievedSource]) -> list[Citation]:
    seen: set[tuple[str, str]] = set()
    citations: list[Citation] = []
    for s in sources:
        key = (s.source_type, s.source_key)
        if key in seen:
            continue
        seen.add(key)
        citations.append(
            Citation(
                sourceType=s.source_type,
                sourceKey=s.source_key,
                title=s.title,
                kind=s.kind,
            )
        )
    return citations


@router.post("/ask", response_model=AskResponse, responses=ASK_ERROR_RESPONSES)
async def ask(
    payload: AskRequest,
    user: CurrentUser,
    provider: Annotated[AIProvider, Depends(ai_provider)],
    rtr: Annotated[Retriever, Depends(retriever)],
    db: Annotated[Session, Depends(get_db)],
) -> AskResponse:
    sources = await rtr.search(db, payload.question, k=6)

    if not sources:
        # Nothing relevant: don't burn an LLM call to say "I don't know".
        record_event(db, action="ask.completed", actor=user, detail="grounded=false")
        return AskResponse(answer=FALLBACK_ANSWER, citations=[], grounded=False)

    result = await provider.chat(
        [
            ChatMessage(role="system", content=SYSTEM_PROMPT),
            ChatMessage(role="user", content=build_grounded_prompt(payload.question, sources)),
        ]
    )
    record_event(
        db,
        action="ask.completed",
        actor=user,
        detail=f"provider={provider.name} sources={len(sources)}",
    )
    return AskResponse(
        answer=result.content,
        citations=_citations(sources),
        grounded=True,
        model=result.model,
    )
